language: python

python:
  - "3.6"

service:
  - postgresql

before_install:
  - export DATABASE_URL_TEST="postgresql://postgres@localhost/test_db"
  - export FLASK_APP=run.py

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - nosetests --with-coverage --cover-package=app

after_script:
  - coveralls