language: python
python:
  - "3.6"
  
service:
  - postgresql


before_install:
  - export DATABASE_URL_TEST="postgresql://postgres@localhost/test_db"
  - export FLASK_APP=run.py
    
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

 before_script:
  - psql -c "CREATE ROLE postgres PASSWORD '123456' CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
  - psql -c 'create database test_db;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

# command to run tests
script: python manage.py test

after_success: "coveralls"