"""empty message

Revision ID: 214f22a335d3
Revises: 4ee5fd4e1ffd
Create Date: 2017-10-06 14:48:07.543912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214f22a335d3'
down_revision = '4ee5fd4e1ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bucketlistitems', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bucketlistitems', 'bucketlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
